-- Database: small_films


SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET client_min_messages = warning;
SET default_tablespace = '';
SET default_with_oids = false;


--DROP DATABASE IF EXISTS films;
CREATE TABLE films
(
    film_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    film_name text NOT NULL,
    year_of_production date NOT NULL,
    CONSTRAINT films_pkey PRIMARY KEY (film_id)
);
--DROP DATABASE IF EXISTS genres;
CREATE TABLE genres
(
    genre_id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    genre_name character varying(32) NOT NULL,
    CONSTRAINT genres_pkey PRIMARY KEY (genre_id)
);
--DROP DATABASE IF EXISTS films_genres;
CREATE TABLE films_genres
(
    film_id integer NOT NULL,
    genre_id integer NOT NULL,
    CONSTRAINT film_genre_pkey PRIMARY KEY (film_id, genre_id),
    CONSTRAINT films_genres_film_id_fkey FOREIGN KEY (film_id)
    REFERENCES films (film_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
    CONSTRAINT films_genres_genre_id_fkey FOREIGN KEY (genre_id)
    REFERENCES genres (genre_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);